# ========================================================
# blog构建打包流水线
# 功能：构建blog静态文件，push到git，输出构建物到制品库
# ========================================================
name: blog-ci-build                   # 定义一个唯一 ID 标识为 blog-ci-build ，名称为 “blog构建打包流水线” 的流水线
displayName: '前端构建流水线'
triggers:                                   # 流水线触发器配置
  push:                                     # 设置 master 分支 在产生代码 push 时精确触发（PRECISE）构建
    - matchType: PRECISE
      branch: master
commitMessage: ''                           # 通过匹配当前提交的 CommitMessage 决定是否执行流水线
stages:                                     # 构建阶段配置
  - stage:                                  # 定义一个 ID 标识为 blog-build-stage ,名为 “Build Stage” 的阶段
      name: blog-build-stage
      displayName: 'Build Stage'
      failFast: false                       # 允许快速失败，即当 Stage 中有任务失败时，直接结束整个 Stage
      steps:                                # 构建步骤配置
        - step: npmbuild@1                  # 采用 npm 编译环境
          name: blog-build               # 定义一个 ID 标识为 blog-build ,名为 “Build Step” 的阶段
          displayName: 'Build Step'
          inputs:                           # 构建输入参数设定
            nodeVersion: 14.15              # 指定 node 环境版本为 14.15
            goals: |                        # 输出 构建环境 Node 和 npm 信息，安装依赖并构建
              node -v
              npm -v
              npm install
              npm run dist
              printf "开始构建和push\n"
              npm run config GITHUB_TOKEN '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'
              npm run clean
              npm run deploy